version: 2
jobs:
  build:
    working_directory: ~/uniforms-patternfly
    docker:
      # Node 8 LTS
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint code
          command: yarn lint
      - run: 
          name: Run tests
          command: yarn coverage
      - store_artifacts:
            path: coverage
            prefix: coverage
  npm_publish:
    working_directory: ~/uniforms-patternfly
    docker:
      # Node 8 LTS
      - image: circleci/node:lts
    steps:
      - checkout
        # Allows us to authenticate with the npm registry
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: CI=true npm run release:prep
      - run: TAG=$CIRCLE_TAG npm run publish

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
          filters:
            tags:
              only: /.*/
      - npm_publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/