name: Release workflow
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: true
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Unit Tests
      run: yarn test
    - name: Publish
      run: echo  "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc && TAG=${GITHUB_REF#"refs/tags/"} npm run release:publish